#!/bin/bash
if [[ ! -L /var/lib/logrotate ]]; then
    rm -fr /var/lib/logrotate
    mkdir -p /shared/state/logrotate
    ln -s /shared/state/logrotate /var/lib/logrotate
fi
if [[ ! -L /var/spool/anacron ]]; then
    rm -fr /var/spool/anacron
    mkdir -p /shared/state/anacron-spool
    ln -s /shared/state/anacron-spool /var/spool/anacron
fi
if [[ ! -d /shared/log/rails ]]; then
    mkdir -p /shared/log/rails
fi
if [[ ! -d /shared/uploads ]]; then
    mkdir -p /shared/uploads
fi
if [[ ! -d /shared/backups ]]; then
    mkdir -p /shared/backups
fi

rm -rf /shared/tmp/{backups,restores}
mkdir -p /shared/tmp/{backups,restores}
