#!/bin/bash
exec 2>&1
# redis
# postgres
cd /var/www/discourse
# before precompile
if [[ -z "$PRECOMPILE_ON_BOOT" ]]; then
    PRECOMPILE_ON_BOOT=1
fi
if [ -f /usr/local/bin/create_db ] && [ "$CREATE_DB_ON_BOOT" = "1" ]; then /usr/local/bin/create_db; fi;
if [ "$MIGRATE_ON_BOOT" = "1" ]; then bundle exec rake db:migrate; fi
if [ "$PRECOMPILE_ON_BOOT" = "1" ]; then SKIP_EMBER_CLI_COMPILE=1 bundle exec rake assets:precompile; fi
LD_PRELOAD=$RUBY_ALLOCATOR bundle exec config/unicorn_launcher -E production -c config/unicorn.conf.rb
